#
# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
language: java
jdk:
 - oraclejdk8
env:
  global:
  - secure: MWDMe0MXiMEYsZrXyueXFJHVARnHMxnoaSsl57GhJGbQOXuoj3zyomMd0eg8OLqyjEB7AecjCD4CbLEW4YIIsbVQ1Od37d4JrTiU/3s1RGDF1j0ilrjFSAntAZBWJ7S1fcaU5rZpDg9LrsxaZVT7pWucESJ6tBxsiPtRcE4LrXNgUlCbbIsapuTf4jfsmcScviS9B0PMhT6VB5iyodpIhojWsC7zayAz7hhMgHJk26y0gCuLlbFlpZdT7xIolGKANAUAic3GScCQaCDL6+ac6IBfKovEPjAhowmzvWVCEKNh1feG1iDwDYxLxqMH1cXksJ/dINEnr6KQ5UddQ860nTskejWBVXQ6CU/6UFx7pYEr/1mqNvq4+lb0qBCbe7eb5XTCxdSKP7VdJT12W7umw7zW0J7u0A5KPFEamUmV/mp8DF+l8nJGfa35nQAhG1uJpxdPZ/trlbtODk6Y9U41RKGHLRXlvxoVqTYkUny3BVqBlNRmkSSlSJgBGTtcFnt7GQIYeS6EQNgDWrVHnlCwoFvRVob/0qIRT6qd1Lp7RHU//vyVCgwt0xWKgnFojWJWMyAUQedccjvyNJsbQAH1K91htVuI+5tr44HOCmIdUgpf18yao63V8Q/QZnEcI09w7j4/U29CGWNIdShozeatWjeEg0MQtToa2Merfc4K5FU=
  - secure: GfmPzsB+EnSaZXXFdf8Dn3Elbmwi9xYgti1U/sJT2U0f9Vy77Gy1YyuKCxZx3EDWvnVSh/7JBUO11fJ1uFLiUDvGEouqW6n1yTjr9MLS2igFCGrpvqrraUs9sLF9yOCGQShhHPI5NDBcGO8Cl0iBstjfJab1GnkACfxw8WTyNxNVEMeZeBm6L0k+OCZwE0Fo0tM2Q1G64wREujucJdkq0zeQL+/967+UMd0J2LymOqSjCGxCl2CkZf41LZFdTqWuiYG0FeOFZkmZgLuk1HDxYG0ajS2j0o+BRNtAlrglLqNuTjFzb7gUQVrgPTjesf+OQT10poE17/v5ShP0sRPjHflS9D5k5yWcZSh+K21RoQtN9+cIu+mffCOgMD2rLZlWFzwkutqPDthn/4eyAEDVYaUAN2E+qA9H/rcWhhNQClqtxlAknb6oY9JmK7CZVhQ2KYXRdLRo7AyBFSZnlFjoQ9d2FD+AFkMP2OsgxxUVgojCFA42UAHqtDqSOyggUU8tcZhHEousHB2ehMkdYOoPoDojy3Bq6HMoGRzlBpkEPNDDSJiRil28rnZlaJVG9//oLMvls3gre5hRjTmACC5guuGWtiIXHFjpNMJxjodkt8R0hXVAzLc/K6vyJDc/nc6Nrm/pMRmuvzKv3BZeuUvnkAYrhmBm6+oZmVfVIX8wxmg=
  - secure: l3rEgG461jLphCQaCpg3dvMBeT3Kdbn8jh5qDKj+7TSyYEK0zgNa6jjzu1JfdEETeLyDT4mkZqwDAzjIMot/brZq16YOAXvKrxkPUneE23kaQh+7bMfXN/3xPClDKN3sTCWQ96JSvLBMqnZdk1i0wdMzxIkw0ApNb0U+k71dmhCt8ItmOEfNpzMWqFwtE7bQ/qgwN1V5c37s/Jbn+UH5elCnTnsS2oemZgzGb9/6n635QbBdptF8rq1Pwm2rXcJuXQVgLz43Szno0riAhwWaZUg/TdHQ2zPMKL+JemVrP8NOlDxp4dSh7FuP0IZYGxE/AAzE7sqOrDJzHUCM7eyeI4tkQF5JW9+9P+p0uaeH65uimTQzJBXSGW/1D6/NjXeHrzmNAJptuCvE4Wj1Nr0SkajZuNO6SmbDjLBRqgKUYxWviurnwE55FSKw1StAKzRkAWDGzBt/WbuHJ3DYv6Pv3mwz+6Tmc7H5SKYyjmnIoyXdMobRR0uNjvCXZViWOagarXzih7FZLm3N9vc51udc94kEwhIPq5ffK+AajMFBgOF8AiVZ904kcG1q8QdteDTudXxs1aVPsmWV/+6x7DJ5P7Jwbt0xGuKtzPtG4KMBq1DUaIR5yjJNy5JPjAQf99Cf5Tht2qL0yeAiNl6nWpQ/8mmcdTGrcXfLx3is74zF0Uk=
  - secure: wqqalUmntmwnkTasW6OwTKjs87ET++xH1ur+fi+mHJgOiT8avdtmuGAtPdtW9QlQ0nqjW+D6Ind9X2Tl7SX7Q2XYfyhB4ybVn5FIvGmfeY7JzkZHOd8CbA18EyqUq3WFaqJWCnEHMJ3Tp7LvdFctanHM57F8YUgjWyY2hbyCg/r9AvuJ3hMWAK5TlHGAi3bT2h3rhzbgq2ka/PmysyDtTlGm4Ll3iTdhY+M2VYdbGfBhzbe0qG00HmTVG4bo22yzKKPD+53hSW8arS05bfYa6QUiVtBEp6EO62Nk8uRALV9KQTrjUaPRm+cD5sOnshQ/rZVtMOLCBkhCSn0+p/HHccFdJ+StIzWYZtk4rakwQlfkZPfZ2N0MXbk7nfH42mNwCbEd5OyDd5AbwxDzaf0SOOKInBqIoPVoRdD40UseJLY/zrtL/YwzfMAqEz0wZd4/ol1X99MPhypZ1dTcTEKv6fJ8NHQkkseZ+EBozXluV43bsUGACgQn+IZ0RyCHxPjtiIM2bDgmh4dhXSxMoQ5MSlf/8cxMdMi+ZytC20qUbpBa4pEtCDha6qJ6nYnCgq5pQdJCb48yITk/rMxg4Ld5LNlBfx+6G+0a/tOPBt6fS5xBgXY0TZalR/Fdag508FxCZbgRhsVtTpkKOjKBK1GeMeWkFO+FshbDfv4o8O7y6OE=
before_install:
- sudo wget https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
- unzip terraform_0.11.3_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- sudo terraform --version

before_script:
- openssl aes-256-cbc -pass "pass:$TRAVIS_CI_SECRET" -in ./.secret -out "$AWS_SSH_KEY"

script: ./gradlew clean --info startSystemTestsWithDocker -DskipServiceInstallation=false
  -Dlog.level=DEBUG -DexecType=DOCKER -PawsExecution=true -Paws_access_key="$AWS_ACCESS_KEY"
  -Paws_secret_key="$AWS_SECRET_KEY" -Paws_region=us-east-2  -Paws_key_name=aws-key-pair
   -Pconfig_path=test/system/aws -Pcred_path=aws-key-pair.pem -Ppravega_org=Prabha-Veerubhotla
  -Ppravega_branch=systemtests_aws -DimageVersion=systemtests_aws -DawsExec=true
sudo: required
services:
  - docker

cache:
  directories:
   - ".gradle"
   - "$HOME/.gradle"
   - "$HOME/.m2"

notifications:
  slack:
    matrix:
      secure: Gv0RJx1Sa/y5fmvLNwY+2ivfWZYCM0ekrr6UAHqsegnid6P/DFZrSrfSpwvcVh2OVNH8DHLV0BoiuDJ7amtl1eMDMXz5/lLz8tFWFKaHv4yDSadm8ILY/KnYUoP4IRuM3NyKQmBrmZB9Or5KFXboG6ex6UkgbuYy0Zyl6syEe168Iw8hlCRx26Jei7/y+8eE2MIGFh09TLRZ/944YbULum9H3KQLYv8nFdPc7GmR5AK461fnwZ7iYjb7MXkCctE5Vml3p9+2Qliv1ZJqNsQeKmSFW6IhiP6pNZ1V8VJEWMQmX/nBr9745l/N+CoLQz9ajLonlxn9xHdWms4TEu1ynFk6uxEJjlcpXcvcEaKhqAKcTMl0GMMRab2m+/Vt3S/VutJnVXQmnhZGT9glLFQHwcdHNqM/LEbXtyisB7zmGImUQpF2InCwO25IXug5gv64IfOHGMzL56yNIhbRgBY9Ud4Tux+pmkV5ZxJiBkul7/FiHQX7tQLUrzQosD0oyCOmaWD7kmbt15A0TOkLgup4HE+sSS1ASwisa7J2+HsbI3Upy3rNVKuIJP0L4KSTn4HSlDlMLLcWM+nz/YCEfuwSRXJTIstotNYHdsLUZAZSYAX7ejpeiuBRed4a4AlCROeKbKKwCcSvqCOjmCaPTpwJAGeJByOXLL2hfQzpDMKCIKM=
    rooms:
      secure: Gv0RJx1Sa/y5fmvLNwY+2ivfWZYCM0ekrr6UAHqsegnid6P/DFZrSrfSpwvcVh2OVNH8DHLV0BoiuDJ7amtl1eMDMXz5/lLz8tFWFKaHv4yDSadm8ILY/KnYUoP4IRuM3NyKQmBrmZB9Or5KFXboG6ex6UkgbuYy0Zyl6syEe168Iw8hlCRx26Jei7/y+8eE2MIGFh09TLRZ/944YbULum9H3KQLYv8nFdPc7GmR5AK461fnwZ7iYjb7MXkCctE5Vml3p9+2Qliv1ZJqNsQeKmSFW6IhiP6pNZ1V8VJEWMQmX/nBr9745l/N+CoLQz9ajLonlxn9xHdWms4TEu1ynFk6uxEJjlcpXcvcEaKhqAKcTMl0GMMRab2m+/Vt3S/VutJnVXQmnhZGT9glLFQHwcdHNqM/LEbXtyisB7zmGImUQpF2InCwO25IXug5gv64IfOHGMzL56yNIhbRgBY9Ud4Tux+pmkV5ZxJiBkul7/FiHQX7tQLUrzQosD0oyCOmaWD7kmbt15A0TOkLgup4HE+sSS1ASwisa7J2+HsbI3Upy3rNVKuIJP0L4KSTn4HSlDlMLLcWM+nz/YCEfuwSRXJTIstotNYHdsLUZAZSYAX7ejpeiuBRed4a4AlCROeKbKKwCcSvqCOjmCaPTpwJAGeJByOXLL2hfQzpDMKCIKM=
  email:
    - arvind.kandhare@dell.com
    - tom.kaitchuck@dell.com
    - andrei.paduroiu@dell.com
    - shivesh.ranjan@dell.com
    - sandeep.shridhar@dell.com
    - Vijayalakshmi.Veerubhotla@emc.com
    - Flavio.Junqueira@emc.com
after_success:
  - bash <(curl -s https://codecov.io/bash) -t ccceafaf-7c60-4a02-9165-480174b535a2
